spring.profiles.active: local
server:
  port: 8080
  ssl:
    enabled: false # Uses self-signed certificate because no key-store configuration is specified.

greeting:
  title: 'hello'

app:
  appName: 'bob'